config {
  hasOutput: true,
  type: "operations",
  schema: dataform.config.vars.RAW_DATA,
  tags: ["LOAD_DATA"]
}


CREATE OR REPLACE TABLE ${ self() }
(
    movieId    INTEGER    NOT NULL
  , imdbId     STRING     NOT NULL
  , tmdbId     INTEGER
);


LOAD DATA INTO ${ self() }
FROM FILES (
  format = "CSV",
  field_delimiter = ",",
  skip_leading_rows = 1,
  allow_jagged_rows = true,
  quote = "\"",
  null_marker = "",
  uris = ["gs://${ dataform.config.vars.LOAD_GCS_BUCKET }/links.csv"]
);
