config {
  type: "table",
  schema: dataform.config.vars.BASE_DATA,
  description: "Contains one rating of one movie by one user",
  dependencies: [ "stg_user_ratings_uniqueKey"],
  assertions: {
    uniqueKey: ["user_id", "movie_id"]
  },
  tags: ["TRANSFORM_DATA"]
}


SELECT
    userId AS user_id
  , movieId AS movie_id
  , rating
  , time
FROM ${ ref({ schema: dataform.config.vars.RAW_DATA, name: "stg_user_ratings" }) }
